version: '3.3'
services:
  datai_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OPENAI_API_KEY: 'openai_api_key'
      DATAI_API_KEY: 'datai_api_key'
    ports:
      - '8000:8000'
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: